# Generated by Django 5.2 on 2025-07-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='recovery_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
